server:
  port: 9096

spring:
  mail:
    username: workforce.solutions.info@gmail.com #TODO ortam değişkeni
    password: ttdtsjkqxoranmhr
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
