server:
  port: 9094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HRPEmployeeDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true