server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/human-resources-requirements-service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update